# Generated by Django 4.1 on 2022-12-07 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_alter_perfil_cep_alter_perfil_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='idade',
        ),
    ]
