# Generated by Django 4.1 on 2022-11-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_produto_desconto_alter_produto_preco_marketing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacao',
            name='desconto',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
