# Generated by Django 4.1 on 2022-12-03 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_variacao_desconto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='descricao_curta',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='descricao_longa',
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='produto',
            name='informacao_tecnica',
            field=models.TextField(default=''),
        ),
    ]
