# Generated by Django 4.1 on 2022-12-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0008_alter_produto_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('S', 'Smartphone'), ('H', 'Hardware'), ('P', 'Periféricos'), ('G', 'Games'), ('E', 'Eletrodomésticos'), ('T', 'TVs')], default=0, max_length=1),
            preserve_default=False,
        ),
    ]
