# Generated by Django 4.1 on 2022-12-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_pedido_qtd_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='variacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
